<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="ConfigDirector.ServerSdk" Version="1.4.0" />
    <PackageVersion Include="ConfigDirector.ServerSdk.AspNetCore" Version="1.4.0" />
    <PackageVersion Include="ConfigDirector.OpenFeature.ServerProvider" Version="1.1.0" />
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageVersion Include="OpenFeature" Version="2.14.1" />
    <PackageVersion Include="OpenFeature.Hosting" Version="2.14.1" />
    <PackageVersion Include="System.Net.ServerSentEvents" Version="10.0.11" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="System.Text.Json" Version="8.0.6" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

</Project>
