<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ConfigDirector.OpenFeature</RootNamespace>
    <VersionPrefix>1.2.0</VersionPrefix>
    <Description>OpenFeature server provider for ConfigDirector, a remote configuration and feature flag service.</Description>
    <PackageTags>$(PackageTags);openfeature;openfeature-provider</PackageTags>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenFeature" />
    <ProjectReference Include="../ConfigDirector.ServerSdk/ConfigDirector.ServerSdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ConfigDirector.OpenFeature.ServerProvider.Tests" />
  </ItemGroup>

</Project>
